### PR TITLE
Adds some element titles for accessibility

### PR DESCRIPTION
**Pull request by jackosmacko**
Adds element titles so people can tell what these buttons are used for. Useful for screen readers.

### CODE REVIEW

**Comment by jackosmacko** [comment]
Might be worth switching this to ion-tooltip instead: https://www.npmjs.com/package/ionic-tooltips 

:|

**Comment by seiyria** [comment]
I fixed the build, so at the very least you should be able to test against the deploy preview here: https://deploy-preview-19--root-twc.netlify.app/

**Comment by jackosmacko** [comment]
Woohoo nice looks good. You can mouse over the icons on the top right and the title will show up now.

**Comment by seiyria** [comment]
Thanks for the contribution!

**Pull request merged**
