### PR TITLE
Start of pt-BR translation

### PR DESCRIPTION
**Pull request by LMituiti**
- Creation of pt-BR files
- Fix of the Hirelings in the calculator (D and R were inverted only the Warm Sun Prophets/Lizard Envoys were correct).
- The translation of the terms, faction names, hirelings and maps in the json are complete so the calculator/randomizer might work with some terms translated.
obs.: The files created are copies of the English version and The Law of Root will be updated to the 7th version in this translatoin.

### CODE REVIEW

**Comment by seiyria** [comment]
Please make sure this passes my build process. When it does, ping me. Thanks!

**Comment by LMituiti** [comment]
> Please make sure this passes my build process. When it does, ping me. Thanks!

Just finished. I've never worked with yaml. I can't use :?

**Comment by seiyria** [comment]
> > Please make sure this passes my build process. When it does, ping me. Thanks!
> 
> Just finished. I've never worked with yaml. I can't use :?

If you use colons in the text, surround it with double quotes. That should make it work correctly.

**Comment by seiyria** [comment]
this looks good. thank you!

**Comment by LMituiti** [comment]
> this looks good. thank you!

Thank you. Sorry for the mistakes. Hope I can finish the translation as soon as possible.

**Pull request merged**
